#Projekt 1 snurrar på Azure
@baseUrl=https://wom-project1.azurewebsites.net/


###Log in to cabins
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test123"
}
