@baseUrl=http://127.0.0.1:5000

#https://shielded-shelf-90510.herokuapp.com
#http://127.0.0.1:5000

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTY2OTlkMzcwMmQyNzdlOGE1YmQzMGQiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjM0MTE3Mzg1LCJleHAiOjE2MzkzMDEzODV9.G9BQk7MhuzvMRowI_x20lgPzfRwTjshlUV3NjfPN7z0

###
GET {{baseUrl}}

### Får stugorna från Projekt1 - API
GET {{baseUrl}}/cabins
Authorization: {{token}}

### Hämta alla bokningar
GET {{baseUrl}}/orders

### Göra en bokning
POST {{baseUrl}}/orders
Content-Type: application/json

{
  "order_date": "December",
  "services_id": "8"  
}

###Radera en bokning
DELETE  {{baseUrl}}/orders/3


###Ändra en bokning
PUT {{baseUrl}}/orders/1
Content-Type: application/json

{
  "order_date": "April"
}


### 
GET {{baseUrl}}/services

### 
POST {{baseUrl}}/services
Content-Type: application/json

{
  "service": "Drinking"  
}

###
PUT {{baseUrl}}/services/
Content-Type: application/json

{
    "service": "Carwashing"  
}


### 
DELETE {{baseUrl}}/services/1

