@baseUrl=http://127.0.0.1:5000/ 


###
GET {{baseUrl}}

### 
POST {{baseUrl}}
Content-Type: application/json

{
  "email": "john@doe.com"  
}

###
PUT {{baseUrl}}
Content-Type: application/json


### 
GET {{baseUrl}}/notes