@baseUrl=http://127.0.0.1:5000

#https://shielded-shelf-90510.herokuapp.com
#http://127.0.0.1:5000

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTY2OTlkMzcwMmQyNzdlOGE1YmQzMGQiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjM0MTE3Mzg1LCJleHAiOjE2MzkzMDEzODV9.G9BQk7MhuzvMRowI_x20lgPzfRwTjshlUV3NjfPN7z0

###
GET {{baseUrl}}

### Får stugorna från Projekt1 - API
GET {{baseUrl}}/cabins
Authorization: {{token}}

### 
GET {{baseUrl}}/orders

### Göra en bokning
POST {{baseUrl}}/orders
Content-Type: application/json

{
  "order_date": "10-10-2021",
  "services_id": "7"  
}

###Radera en bokning
DELETE  {{baseUrl}}/orders/2


###Ändra en bokning
PUT {{baseUrl}}/orders/5
Content-Type: application/json

{
  "order_date": "02-10-2021" 
}


### 
GET {{baseUrl}}/services

### 
POST {{baseUrl}}/services
Content-Type: application/json

{
  "service": "Cleaning the garden"  
}

###
PUT {{baseUrl}}/services/7
Content-Type: application/json

{
    "service": "Cleaning garden+garage"  
}


### 
DELETE {{baseUrl}}/services/6

